import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import StoreProvider from './providers/StoreProvider';
import { cookies } from 'next/headers';
import axios from 'axios';
import { getUserData } from '@/utils/functions/users';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUserData();

  return (
    <html lang="en">
      <StoreProvider user={user}>
        <body className={`${inter.className} bg-primary-100`}>{children}</body>
      </StoreProvider>
    </html>
  );
}
